In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

In [2]:
from sklearn.tree import DecisionTreeClassifier

In [3]:
clf = DecisionTreeClassifier(random_state=1024)

In [4]:
iris = load_iris()

In [9]:
cross_val_score(clf, X=iris.data, y=iris.target, cv=20, verbose=True)

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.1s finished


array([ 1.        ,  1.        ,  0.88888889,  1.        ,  1.        ,
        1.        ,  0.77777778,  0.88888889,  1.        ,  0.77777778,
        1.        ,  0.83333333,  1.        ,  1.        ,  0.83333333,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [11]:
print(clf.classes_)

None


In [13]:
clf.fit(iris.data, iris.target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=1024, splitter='best')

In [14]:
clf.classes_

array([0, 1, 2])

In [15]:
clf.feature_importances_

array([ 0.02666667,  0.        ,  0.05072262,  0.92261071])

In [18]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='|S10')

In [19]:
clf.max_features_

4

In [20]:
clf.apply(iris.data)

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5, 14,  5,  5,  5,  5,  5,  5, 10,  5,  5,  5,  5,  5, 10,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 16, 16,
       16, 16, 16, 16,  6, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
        8, 16, 16, 16, 16, 16, 16, 15, 16, 16, 11, 16, 16, 16,  8,  8, 16,
       16, 16, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16])

In [21]:
clf.decision_path(iris.data)

<150x17 sparse matrix of type '<type 'numpy.int64'>'
	with 560 stored elements in Compressed Sparse Row format>

In [23]:
clf.get_params()

{'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_split': 1e-07,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': False,
 'random_state': 1024,
 'splitter': 'best'}